#!/bin/bash

# Commands to apply a Bayesian neural network to the binary response problem.

net-spec log 2 16 1 / ih=0.05:0.5 bh=0.05:0.5 ho=x0.05:0.5 bo=100 
model-spec log binary

data-spec log 2 1 2 / bdata@1:300 . bdata@301: .

net-gen log fix 0.5
mc-spec log repeat 10 sample-noise heatbath hybrid 100:10 0.2
net-mc log 1

mc-spec log repeat 10 sample-sigmas heatbath 0.95 hybrid 100:10 0.3 negate
net-mc log 30

net-pred mpa log 11:
