#!/bin/bash

# Commands to train a neural network on the binary response problem using
# gradent descent training.

net-spec log 2 15 1 / ih=+ bh=+ ho=+ bo=+
model-spec log binary

data-spec log 2 1 2 / bdata@1:800 .

net-gd log 100000 1000 / 0.4 batch

net-pred nmpa log 100000 / bdata@801: .
