#!/bin/bash

log=log

  net-spec $log 36 272 softplus cfg-b:bconfigx cfg-i:iconfigx 4 cfg-h:hconfigx \
                / ih=0.2:2 bh=0.3:2 ho=0.1:2 bo=0.1:2
  model-spec $log class
  
  data-spec $log 36 1 4 / idata@1:3997 .
  
  net-gen $log fix 0.1

  mc-spec $log repeat 10 heatbath hybrid 80:20 0.04
  net-mc $log 1

  mc-spec $log repeat 2 sample-sigmas heatbath hybrid 300:30 0.05
  net-mc $log 3

net-pred nmpa $log 3: / idata@5001:5100 .
