#!/bin/bash

net-spec log 36 272 softplus 4 \
   / ih=0.2:2 config:iconfigx bh=0.3:2 config:bconfigx \
     ho=0.1:2 config:hconfigx bo=0.1:2
model-spec log class
  
data-spec log 36 1 4 / idata@1:3997 .
  
net-gen log fix 0.1

mc-spec log repeat 10 heatbath hybrid 80:20 0.04
net-mc log 1

mc-spec log repeat 2 sample-sigmas heatbath hybrid 300:30 0.05
net-mc log 3

net-pred nmpa log 3: / idata@5001:5100 .
