#!/bin/bash

net-spec log 36 80 softplus 4 \
      / ih=0.2:2 config:iconfig bh=0.3:2 config:bconfig \
        ho=0.1:2 config:hconfig bo=0.1:2
model-spec log class
  
data-spec log 36 1 4 / idata@1:4999 .
  
net-gen log fix 0.1

mc-spec log repeat 10 heatbath hybrid 100:20 0.04
net-mc log 1

mc-spec log repeat 2 sample-sigmas heatbath hybrid 500:40 0.05
net-mc log 4

net-pred nmpa log 3: / idata@5001:5100 .
