#!/bin/bash



  net-spec log 36 \
                20 softplus 20 softplus 20 softplus 20 softplus 20 softplus \
                10 4 \
                / ih0=0.2:2 ih1=0.2:2 ih2=0.2:2 ih3=0.2:2 ih4=0.2:2 \
                  bh0=0.3:2 bh1=0.3:2 bh2=0.3:2 bh3=0.3:2 bh4=0.3:2 \
                  h0h5=0.1:2 h1h5=0.1:2 h2h5=0.1:2 h3h5=0.1:2 h4h5=0.1:2 \
                  bh5=0.1:2 h5o=0.1:2 bo=0.1:2 
  model-spec log class
  
  data-spec log 36 1 4 / idata@1:499 .
  
  net-gen log fix 0.1

  mc-spec log met-1 1.5
  net-mc log 5

net-pred nmpa log 4: / idata@5001:5100 .
