#!/bin/bash

if [ x$system == x ]; then system=$SYSTEM; fi
if [ x$precision == x ]; then precision=flt; fi

n=1
for i in res-$system-*/$precision; do
  echo $n `echo $i | sed "s,/.*,," | sed "s,.*-,,"`
  n=`calc 1+$n`
done
