#!/bin/bash

if [ x$1 == x ]; then
  echo "Usage: run-ex <ex>..."
  exit 1
fi

if [ x$SYSTEM == x ]; then
  dir=res
else
  dir=res-$SYSTEM
fi

export INFO=1

for w in dbl flt; do
  for p in $@; do 
    mkdir -p $dir-$p
    ( echo -n "Commit: "; git rev-parse HEAD
      echo; echo Running $p with $w:; echo
      using $w /bin/time -f "elapsed %es" $p
    ) >& $dir-$p/$w
    echo -n "For $p with $w on CPU: " 
    grep "^elapsed " $dir-$p/$w
  done
done
