#!/bin/bash

if [ "x$@" == x ]; then
  TESTS="test-func3 test-func2 test-func test-config test-adj test-stepsizes \
         test-class test-nonseq test-sparse test-offsets test-im \
         test-sigmas test-one-point test-dyn test-hmc"
else
  TESTS="$@"
fi

mkdir -p out

for test in $TESTS; do
  echo RUNNING $test
  $test >& out/$test
  diff save/$PRECISION/$test out/$test
  echo DONE $test
done
