#!/bin/bash

if [ x$1 == x ]; then
  echo "Usage: run-ex-gpu <ex>..."
  exit 1
fi

if [ x$SYSTEM == x ]; then
  dir=res
else
  dir=res-$SYSTEM
fi

if [ x$GPUNAME == x ]; then
  GPUNAME=gpu
  unset GPU
else
  eval GPU=\$$GPUNAME
  export GPU
fi

export INFO=1

PROG=`echo $0 | sed s@.*/@@`
if [ $PROG == run-ex-gpu ]; then
  WHAT="dbl-gpu flt-gpu"
elif [ $PROG == run-ex-flt-gpu ]; then
  WHAT=flt-gpu
elif [ $PROG == run-ex-dbl-gpu ]; then
  WHAT=dbl-gpu
else
  echo Something wrong! $PROG
  exit 1
fi

for w in $WHAT; do
  for p in $@; do 
    mkdir -p $dir-$p
    ( echo -n "Commit: "; git rev-parse HEAD
      echo; echo Running $p with $w on $GPUNAME:; echo
      using $w /bin/time -f "elapsed %es" $p
    ) >& $dir-$p/$w-$GPUNAME
    echo -n "For $p with $w on $GPUNAME: " 
    grep "^elapsed " $dir-$p/$w-$GPUNAME
  done
done
