#!/bin/bash

set -e

if [ x$1 == x ]; then
  echo "Usage: run-ex <ex>..."
  exit 1
fi

if [ x$SYSTEM == x ]; then
  dir=res
else
  dir=res-$SYSTEM
fi

export INFO=1

PROG=`echo $0 | sed s@.*/@@`
if [ $PROG == run-ex ]; then
  WHAT="dbl flt"
elif [ $PROG == run-ex-flt ]; then
  WHAT=flt
elif [ $PROG == run-ex-dbl ]; then
  WHAT=dbl
else
  echo Something wrong! $PROG
  exit 1
fi

for w in $WHAT; do
  for p in $@; do 
    mkdir -p $dir-$p
    ( echo -n "Commit: "; git rev-parse HEAD
      echo; echo Running $p with $w:; echo
      using $w /bin/time -f "elapsed %es" $p
    ) >& $dir-$p/$w
    echo -n "For $p with $w on CPU: " 
    grep "^elapsed " $dir-$p/$w
  done
done
