#!/bin/bash

net-spec log 5 1 omit:3 / ti=2 io=3
model-spec log real 4
data-spec log 5 1 / "% echo 1 3 4 2 5 22" .
net-gen log fix - <<end
-0.35  +0.19  -0.90  -3.33  +2.29
-2.35  -3.58  -0.56  -1.13
end
net-display log
net-tbl -h o0@ log 0
net-grad-test log 0 0.001

