#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 5 2 identity 1 / ih=15 omit:2,4 bh=4 ho=25 io=30
data-spec log 5 1 / "%echo 11 7 22 8 33 5000000" .
model-spec log real 10000
net-gen log fix - <<end
10 1000 20 2000 30 3000
50 60
1000 20
5000 4000 3000 2000 1000
end
net-display log 0
net-tbl -h x0@x1@x2@x3@x4@ log 0
net-tbl -h o0@ log 0
calc i1=11 i2=7 i3=22 i4=8 i5=33 \
 "(i1*10+i3*20+i5*30+50)*1000 + (i1*1000+i3*2000+i5*3000+60)*20 \
     + (i1*5000+i2*4000+i3*3000+i4*2000+i5*1000)"
net-tbl -h u0u100u200 log 0
net-tbl -h u0@u100@u200@ log 0
calc i1=11 i2=7 i3=22 i4=8 i5=33 "i1*10+i3*20+i5*30+50"
calc i1=11 i2=7 i3=22 i4=8 i5=33 "i1*1000+i3*2000+i5*3000+60"
net-grad-test log 0 0.005

echo " "; echo "--- B"; echo " "

net-spec log 5 2 1 / ih=15 omit:2,4 bh=4 ho=25 io=30
data-spec log 5 1 / "%echo 1.1 .7 2.2 .8 3.3 100" .
model-spec log real 1000
net-gen log fix - <<end
1.0 -1.1 2.0 -2.2 3.0 -3.3
-0.5 0.6
1 2
50 40 30 20 10
end
net-display log 0
net-tbl -h x0@x1@x2@x3@x4@ log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.002

echo " "; echo "--- C"; echo " "

net-spec log 5 2 7 1 / ih=15 bh=4 hh=2 ho=25
data-spec log 5 1 / "%echo 1.1 .7 2.2 .8 2.3 100" .
model-spec log real 10
net-gen log fix - <<end
1.0 -1.1 -2.9 -1.2 0.9 -1.3 1.1 1.2 1.3 1.4
-0.5 0.6
.1 .2 .3 .4 .5 .6 .7 .8 .9 1.0 1.1 1.2 1.3 1.4
.1 .2 .3 .4 .5 .6 .7
end
net-display log 0
net-tbl -h x0@x1@x2@x3@x4@ log 0
net-eval -h0 -o log 0 / 1.1 1.1 0 / 0.7 0.7 0 / 2.2 2.2 0 / 0.8 0.8 0 / 3.3 3.3 0
net-eval -h1 -o log 0 / 1.1 1.1 0 / 0.7 0.7 0 / 2.2 2.2 0 / 0.8 0.8 0 / 3.3 3.3 0
net-eval log 0 / 1.1 1.1 0 / 0.7 0.7 0 / 2.2 2.2 0 / 0.8 0.8 0 / 3.3 3.3 0 
net-tbl -h o0@ log 0
net-tbl -h b@ log 0
net-grad-test log 0 0.002

echo " "; echo "--- D"; echo " "

net-spec log 5 3 identity 1 / ti=1 ih=15 omit:2,4 bh=4 ho=25 io=30
data-spec log 5 1 / "%echo 11 7 22 8 33 5000000" .
model-spec log real 10000
net-gen log fix - <<end
1 2 3 4 5
10 0 1000 20 0 2000 30 0 3000
50 0 60
1000 0 20
5000 4000 3000 2000 1000
end
net-display log 0
net-tbl -h x0@x1@x2@x3@x4@ log 0
net-tbl -h o0@ log 0
calc i1=11+1 i2=7+2 i3=22+3 i4=8+4 i5=33+5 \
 "(i1*10+i3*20+i5*30+50)*1000 + (i1*1000+i3*2000+i5*3000+60)*20 \
     + (i1*5000+i2*4000+i3*3000+i4*2000+i5*1000)"
net-grad-test log 0 0.002

echo " "; echo "--- E"; echo " "

net-spec log 1 3 identity 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 1.5
1 10 20
end
net-display log 0
net-tbl -h o0@ log 0
calc "(-1) + 10*(1) + 20*(1.5)"
net-grad-test log 0 0.003

echo " "; echo "--- F"; echo " "

net-spec log 1 3 tanh 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 1.5
1 10 20
end
net-display log 0
net-tbl -h o0@ log 0
calc "Tanh(-1) + 10*Tanh(1) + 20*Tanh(1.5)"
net-grad-test log 0 0.003

echo " "; echo "--- G"; echo " "

net-spec log 1 3 softplus 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 1.5
1 10 20
end
net-display log 0
net-tbl -h o0@ log 0
calc "Log(1+Exp(-1)) + 10*Log(1+Exp(1)) + 20*Log(1+Exp(1.5))"
net-grad-test log 0 0.003

echo " "; echo "--- H"; echo " "

net-spec log 1 3 softplus0 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 1.5
1 10 20
end
net-display log 0
net-tbl -h o0@ log 0
calc l2="Log(2)" \
     "(Log(1+Exp(-1))-l2) + 10*(Log(1+Exp(1))-l2) + 20*(Log(1+Exp(1.5))-l2)"
net-grad-test log 0 0.003

echo " "; echo "--- I"; echo " "

net-spec log 1 4 normalize 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 3 2
1 10 20 2
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc s="Sqrt(0.01+((-1)^2+1^2+3^2+2^2)/4)" "(-1)/s"
calc s="Sqrt(0.01+((-1)^2+1^2+3^2+2^2)/4)" "1/s"
calc s="Sqrt(0.01+((-1)^2+1^2+3^2+2^2)/4)" "3/s"
calc s="Sqrt(0.01+((-1)^2+1^2+3^2+2^2)/4)" "2/s"
calc s="Sqrt(0.01+((-1)^2+1^2+3^2+2^2)/4)" "1*(-1)/s+10*1/s+20*3/s+2*2/s"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

net-spec log 1 4 normalize%2 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 3 2
1 10 20 2
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc s1="Sqrt(0.01+((-1)^2+3^2)/2)" s2="Sqrt(0.01+(1^2+2^2)/2)" "(-1)/s1"
calc s1="Sqrt(0.01+((-1)^2+3^2)/2)" s2="Sqrt(0.01+(1^2+2^2)/2)" "1/s2"
calc s1="Sqrt(0.01+((-1)^2+3^2)/2)" s2="Sqrt(0.01+(1^2+2^2)/2)" "3/s1"
calc s1="Sqrt(0.01+((-1)^2+3^2)/2)" s2="Sqrt(0.01+(1^2+2^2)/2)" "2/s2"
calc s1="Sqrt(0.01+((-1)^2+3^2)/2)" s2="Sqrt(0.01+(1^2+2^2)/2)" \
     "1*(-1)/s1+10*1/s2+20*3/s1+2*2/s2"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

net-spec log 1 4 normalize/2 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 3 2
1 10 20 2
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc s1="Sqrt(0.01+((-1)^2+1^2)/2)" s2="Sqrt(0.01+(3^2+2^2)/2)" "(-1)/s1"
calc s1="Sqrt(0.01+((-1)^2+1^2)/2)" s2="Sqrt(0.01+(3^2+2^2)/2)" "1/s1"
calc s1="Sqrt(0.01+((-1)^2+1^2)/2)" s2="Sqrt(0.01+(3^2+2^2)/2)" "3/s2"
calc s1="Sqrt(0.01+((-1)^2+1^2)/2)" s2="Sqrt(0.01+(3^2+2^2)/2)" "2/s2"
calc s1="Sqrt(0.01+((-1)^2+1^2)/2)" s2="Sqrt(0.01+(3^2+2^2)/2)" \
     "1*(-1)/s1+10*1/s1+20*3/s2+2*2/s2"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

echo " "; echo "--- J"; echo " "

net-spec log 1 4 softmax 1 / ih=10 ho=25
data-spec log 1 1 / "%echo 1 1" .
model-spec log real 10
net-gen log fix - <<end
-1 1 3 2
1 10 20 2
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc s="Exp(-1)+Exp(1)+Exp(3)+Exp(2)" "Exp(-1)/s"
calc s="Exp(-1)+Exp(1)+Exp(3)+Exp(2)" "Exp(1)/s"
calc s="Exp(-1)+Exp(1)+Exp(3)+Exp(2)" "Exp(3)/s"
calc s="Exp(-1)+Exp(1)+Exp(3)+Exp(2)" "Exp(2)/s"
calc s="Exp(-1)+Exp(1)+Exp(3)+Exp(2)" "(Exp(-1)+10*Exp(1)+20*Exp(3)+2*Exp(2))/s"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

echo " "; echo "--- K"; echo " "

net-spec log 1 4 softmax/2 1 / ih=100 ho=100
data-spec log 1 1 / "%echo 1 3" .
model-spec log real 1
net-gen log fix - <<end
-1 1 3 2
1 1 1 1
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc "1/(1+Exp(-2))"
calc "1/(1+Exp(-1))"
net-grad-test log 0 0.003
net-stepsizes log 0 0.001

echo " "; echo "--- L"; echo " "

net-spec log 1 4 softmax%2 1 / ih=100 ho=100
data-spec log 1 1 / "%echo 1 3" .
model-spec log real 1
net-gen log fix - <<end
-1 1 3 2
1 1 1 1
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc "1/(1+Exp(-4))"
calc "1/(1+Exp(-1))"
net-grad-test log 0 0.003
net-stepsizes log 0 0.001

echo " "; echo "--- M"; echo " "

net-spec log 1 4 softmax/2 1 / ih=100 ho=100
data-spec log 1 1 / "%echo 1 3" .
model-spec log real 1
net-gen log fix - <<end
-75 -70 75 70
1 1 1 1
end
net-display log 0
net-tbl -h u100@u200@u300@u400@ log 0
net-tbl -h o0@ log 0
calc "1/(1+Exp(-5))"
net-grad-test log 0 0.003
net-stepsizes log 0 0.001

echo " "; echo "--- N"; echo " "

net-spec log 1 2 identity 2 identity product:0 1 / ih0=10 ih1=10 h1o=10
data-spec log 1 1 / "%echo 1 1000" .
model-spec log real 10000
net-gen log fix - <<end
3 4 5 6
100 1000
end
net-display log 0
net-tbl -h u100@u200@u101@u201@ log 0
net-tbl -h o0@ log 0
net-eval -i -h log 0 / 1 1 0
calc "3*5*100 + 4*6*1000"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

echo " "; echo "--- O"; echo " "

net-spec log 1 2 identity 2 identity product:0.2 1 / ih0=10 ih1=10 h1o=10
data-spec log 1 1 / "%echo 1 1000" .
model-spec log real 10000
net-gen log fix - <<end
3 4 5 6
100 1000
end
net-display log 0
net-tbl -h u100@u200@u101@u201@ log 0
net-tbl -h o0@ log 0
net-eval -i -h log 0 / 1 1 0
calc "4*5*100 + 4*6*1000"
net-grad-test log 0 0.001
net-stepsizes log 0 0.001
