#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 3 2 / io=3 bo=4
data-spec log 3 2 / "%echo 100 200 300 17 18" .
model-spec log real 1
net-gen log fix - <<end
2 3 4 5 6 7 40 50
end
net-display log 0
net-tbl -h x0@x1@x2@ log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

mc-spec log heatbath dynamic 1 0.2
net-mc log 10
net-grad-test log 10 0.001
net-tbl -h tKEb log 0:
net-tbl -h q0q1q2q3q4 log
net-tbl -h q5q6q7o0@o1@ log

echo " "; echo "--- B"; echo " "

net-spec log 3 2 / io=3 bo=4
(echo 100 200 300 17 18; echo 101 202 300 17.1 18.2) >data
data-spec log 3 2 / data .
model-spec log real 1
net-gen log fix - <<end
2 3 4 5 6 7 40 50
end
net-display log 0
net-tbl -h x0@x1@x2@ log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

mc-spec log heatbath dynamic 1 0.2
net-mc log 10
net-grad-test log 10 0.001
net-tbl -h tKEb log 0:
net-tbl -h q0q1q2q3q4 log
net-tbl -h q5q6q7o1@ log

echo " "; echo "--- C"; echo " "

net-spec log 3 2 / io=3 bo=4
(echo 100 200 300 17 18; echo 101 202 300 17.1 18.2) >data
data-spec log 3 2 / data .
model-spec log real 1
net-gen log fix - <<end
2 3 4 5 6 7 40 50
end
net-display log 0
net-tbl -h x0@x1@x2@ log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

mc-spec log repeat 10 heatbath dynamic 1 0.2
net-mc log 1
net-grad-test log 1 0.001
net-tbl -h tKEb log 0:
net-tbl -h q0q1q2q3q4 log
net-tbl -h q5q6q7o1@ log

echo " "; echo "--- D"; echo " "

net-spec log 3 2 / io=3 bo=4
(echo 100 200 300 17 18; echo 101 202 300 17.1 18.2) >data
data-spec log 3 2 / data .
model-spec log real 1
net-gen log fix - <<end
2 3 4 5 6 7 40 50
end
net-display log 0
net-tbl -h x0@x1@x2@ log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

mc-spec log heatbath dynamic 10 0.2
net-mc log 3
net-grad-test log 3 0.001
net-tbl -h tKEb log 0:
net-tbl -h q0q1q2q3q4 log
net-tbl -h q5q6q7o1@ log
