#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 5 1 / ti=2 io=3 omit:3
model-spec log real 4
data-spec log 5 1 / "% echo 1 3 4 2 5 22" .
net-gen log fix - <<end
-0.35  +0.19  -0.90  -3.33  +2.29
-2.35  -3.58  -0.56  -1.13
end
net-display log
net-tbl -h o0@ log 0
net-grad-test log 0 0.001
net-stepsizes log 0 0.001

echo " "; echo "--- B"; echo " "

net-spec log 1 1 identity 1 / ih=3 th=4 ho=5
model-spec log real 6
data-spec log 1 1 / "%echo 0.1 3" .
net-gen log fix - <<end
4 2 3
end
net-display log
net-grad-test log 0 0.001
net-stepsizes log 0 0.001
net-eval -h log 0 / "%echo 0.1 3"
net-tbl u100@ log 0

echo " "; echo "--- C"; echo " "

net-spec log 1 1 1 / ih=3 th=4 ho=5
model-spec log real 6
data-spec log 1 1 / "%echo 0.1 3" .
net-gen log fix - <<end
4 2 3
end
net-display log
net-grad-test log 0 0.001
net-stepsizes log 0 0.001
net-eval -h log 0 / "%echo 0.1 3"
net-tbl u100@ log 0
