#!/bin/bash

# Set up so that, even in single precision, the arithmetic should be exact, so
# results with all versions (flt, flt-gpu, dbl, dbl-gpu) should be identical.

echo " "; echo "--- A"; echo " "

net-spec log 1 1 / io=2
data-spec log 1 1 / "%echo 3 37" .
model-spec log real 1
echo 10 | net-gen log fix -
net-display log 0
net-tbl o0@bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- B"; echo " "

net-spec log 1 1 / io=2 bo=2
data-spec log 1 1 / "%echo 3 37" .
model-spec log real 1
echo 10 2 | net-gen log fix -
net-display log 0
net-tbl o0@bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- C"; echo " "

net-spec log 1 1 / io=2 bo=2
(echo 3 37; echo 2 26) >data
data-spec log 1 1 / data .
model-spec log real 1
echo 10 2 | net-gen log fix -
net-display log 0
net-tbl o0@bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- D"; echo " "

net-spec log 1 1 / io=2 bo=2
(echo 3 37; echo 2 26; echo 1 9) >data
data-spec log 1 1 / data .
model-spec log real 1
echo 10 2 | net-gen log fix -
net-display log 0
net-tbl o0@bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- E"; echo " "

net-spec log 2 2 / io=2 bo=2
(echo 3 1 37 4; echo 2 2 21 7; echo 1 7 39 -2) >data
data-spec log 2 2 / data .
model-spec log real 1
echo 10 1 3 -1 2 1 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl o1@ log 0
net-tbl bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- F"; echo " "

net-spec log 2 2 / io=2 bo=2
(echo 3 1 37 4; echo 2 2 21 7; echo 1 7 39 -2; echo 2 2 20 7) >data
data-spec log 2 2 / data .
model-spec log real 1
echo 10 1 3 -1 2 1 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl o1@ log 0
net-tbl bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- G"; echo " "

net-spec log 2 2 / io=2 bo=2
(echo 1 7 38 -2; echo 3 1 37 4; echo 2 2 21 7; echo 1 7 39 -2; echo 2 2 22 7) \
 >data
data-spec log 2 2 / data .
model-spec log real 1
echo 10 1 3 -1 2 1 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl o1@ log 0
net-tbl bE log 0
net-grad-test log 0 0.5

echo " "; echo "--- H"; echo " "

net-spec log 10 11 identity 9 identity 2 \
          / bh0=4 bh1=4 bo=4 ih0=4 ih1=4 io=4 hh=4 h1o=4 h0o=4 
(echo 6 -1 2 -3 5 5 6 -6 -4 -7 -6192 56920; 
 echo -10 11 -12 15 14 -15 -16 13 18 -9 1087 40300) >data
data-spec log 10 2 / data .
model-spec log real 1
cat >wts <<end
-11 12 3 14 15 16 -7 18 19 11 -9
-11 2 3 4 5 16 7 -8 -9 11 -8
-1 1 3 4 -5 6 17 6 1 11 -7
-11 2 3 -4 15 16 7 18 19 11 -6
-1 12 3 1 -5 6 7 -8 9 11 -5
-11 12 -3 4 5 -26 7 -18 19 11 -4
-1 1 3 -4 5 6 17 8 19 11 -3
-1 2 -13 -4 5 -16 17 28 19 11 -2
-1 2 3 4 -12 2 7 18 29 11 -1
-11 12 3 11 12 16 17 38 19 11 -1
0 1 -13 3 -21 30 6 -60 -10 40 8
end
cat >>wts <<end
-27 11 2 13 -14 15 6 17 18
11 35 22 13 14 5 16 17 -2
3 12 12 -13 14 -15 16 7 8
-11 12 13 -24 4 15 6 -7 8
2 12 -3 4 -30 15 16 17 1
11 2 3 4 15 -13 -6 17 8
1 -2 3 4 5 -1 6 -1 -3
1 1 3 4 5 16 -17 7 8
-11 2 13 14 15 16 7 18 -7
11 2 13 4 1 6 7 28 9
1 12 3 4 5 16 7 8 -50
-8 7 12 -3 4 15 16 17 -1
11 1 2 3 4 5 16 17 8
1 12 8 -13 1 5 1 7 8
11 2 13 13 -14 15 16 17 8
-11 -12 1 14 -10 5 16 17 8
1 2 13 14 5 -5 16 17 8
11 2 3 -14 15 6 6 77 1
-11 2 3 4 5 16 7 27 18
11 -12 3 14 5 6 7 18 -18
1 12 3 4 5 -16 7 26 -9
1 2 3 -14 5 6 21 8 18
end
cat >>wts <<end
37 -30
32 -33
40 -35
34 -32
43 -39
37 -39
42 -38
38 -34
35 -37
-7 10
-1 2
-2 3
-3 15
-4 7
-8 11
-4 11
-3 7
-8 5
-1 3
-0 1
-1 12
-1 11
-2 3
-3 15
-4 7
-5 11
-6 1
-7 17
-3 5
-1 13
7 3
end
net-gen log fix - <wts
net-display log 0
net-tbl o0@o1@E log 0
net-grad-test log 0 0.125

echo " "; echo "--- I"; echo " "

net-spec log 2 2 square 1 / ih=2 bh=4 ho=8
(echo 1 7 3040; echo 3 1 1200; echo 2 2 1030; echo 1 7 3040; echo 2 2 1028) \
 >data
data-spec log 2 1 / data .
model-spec log real 1
echo 4 1 3 -1 2 1 4 5 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl bE log 0
net-grad-test log 0 0.03125

echo " "; echo "--- J"; echo " "

net-spec log 2 2 cube 1 / ih=2 bh=4 ho=8
(echo 1 3 -3.5; echo 3 1 7.25; echo 2 2 -1.5; echo 1 4 -32; echo 2 2 -1) \
 >data
data-spec log 2 1 / data .
model-spec log real 1
echo -2 1 0.5 -1 1.5 1 2 5 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl bE log 0
net-grad-test log 0 0.0625

echo " "; echo "--- J"; echo " "

net-spec log 2 2 identity 1 / ih=2 bh=1 ho=4 bo=1
(echo 1 3 -3.5; echo 3 1 7.25; echo 2 2 -1.5; echo 1 4 -32; echo 2 2 -1) \
 >data
data-spec log 2 1 / data .
model-spec log real 1
echo -2 1 0.5 -1 1.5 1 2 5 -1 | net-gen log fix -
net-display log 0
net-tbl o0@ log 0
net-tbl bE log 0
net-grad-test log 0 0.0625
