#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 5 \
             4 input-config:"%echo  3 1 1  4 2 1  1 1 2" \
             3 hidden-config:"%echo 1 2 1  2 1 1" \
             1 / ih=7 hh=8 ho=9
net-spec log config
data-spec log 5 1 / "%echo 2 3 4 5 6 7" .
model-spec log real 5
net-gen log fix - <<end
0.1 0.2 0.3 5 6 7
end
net-display log 0
net-tbl q0q1q2q3q4 log 0
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0
calc "6*Tanh(0.3*Tanh(1.3*0.1+1.1*0.2)) + 5*Tanh(0.3*Tanh(1.4*0.1))"
net-grad-test log 0 0.002

echo " "; echo "--- B"; echo " "

net-spec log 5 \
             4 input-config:"%echo  3 1 1  + + 1  1 1 +" \
             3 hidden-config:"%echo 1 2 1  +1 -1 1" \
             1 / ih=7 hh=8 ho=9
net-spec log config

net-spec log 2 3 input-config:"%echo + + 1 = + + + -1 = 1 +2 -" 1 / ih=2 ho=3
net-spec log config

echo " "; echo "--- C"; echo " "

echo "-- fully connected --"

net-spec log 2 2 2 1 / ih=3 hh=4 ho=5 bo=10
net-spec log 
model-spec log real 1:1
data-spec log 2 1 / "%echo 2 3 4" .
net-gen log 0
net-display log 0
net-grad-test log 0 0.002
net-stepsizes log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0

mc-spec log sample-noise heatbath hybrid 100 0.2
net-mc log 3
net-display log

echo " "

echo "-- fully connected the hard way --"

net-spec log 2 \
             2 input-config:"%echo  1 1 1  1 2 2  2 1 3  2 2 4" \
             2 hidden-config:"%echo 1 1 1  1 2 2  2 1 3  2 2 4" \
             1 / ih=3 hh=4 ho=5 bo=10
net-spec log config
model-spec log real 1:1
data-spec log 2 1 / "%echo 2 3 4" .
net-gen log 0
net-display log 0
net-grad-test log 0 0.002
net-stepsizes log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0

mc-spec log sample-noise heatbath hybrid 100 0.2
net-mc log 3
net-display log

echo " "

echo " "; echo "--- D"; echo " "

echo "-- fully connected --"

net-spec log 2 2 2 1 / ih=3:2 hh=4:2 ho=5 bo=10
net-spec log 
model-spec log real 1:1
data-spec log 2 1 / "%echo 2 3 4" .
net-gen log 0
net-display log 0
net-grad-test log 0 0.002
net-stepsizes log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0

mc-spec log sample-sigmas heatbath hybrid 100 0.2
net-mc log 3
net-display log

echo " "

echo "-- fully connected the hard way --"

net-spec log 2 \
             2 input-config:"%echo  1 1 1  1 2 2  2 1 3  2 2 4" \
             2 hidden-config:"%echo 1 1 1  1 2 2  2 1 3  2 2 4" \
             1 / ih=3:2 hh=4:2 ho=5 bo=10
net-spec log config
model-spec log real 1:1
data-spec log 2 1 / "%echo 2 3 4" .
net-gen log 0
net-display log 0
net-grad-test log 0 0.002
net-stepsizes log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0

mc-spec log sample-sigmas heatbath hybrid 100 0.2
net-mc log 3
net-display log

echo " "

echo " "; echo "--- E"

net-spec log 10 8 identity input-config:filter1 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

net-spec log 10 8 identity input-config:filter2 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

net-spec log 10 8 identity input-config:filter3 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

net-spec log 10 8 identity input-config:filter4 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

net-spec log 10 8 identity input-config:filter5 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

net-spec log 10 8 identity input-config:filter6 1 / ih=1 ho=1 bo=1
model-spec log binary

net-spec log config
net-gen log 
net-display log 0

echo " "; echo "--- F"; echo " "

net-spec log 5 \
             4 input-config:"%echo  2+1 1 1  5-1 2 1  +102-106+1 1 2" \
             3 hidden-config:"%echo 1 2 1  -477+478 1 1" \
             1 / ih=7 hh=8 ho=9
net-spec log config

echo " "; echo "--- G"; echo " "

net-spec log 5 \
             4 input-config:"%echo  + + 1  = + +  + -1 =  1 +2 -" \
             1 / ih=7
net-spec log config

net-spec log 5 \
             4 input-config:"%echo  + + 1  = + +  + -1 =  7-6 +102-100 -" \
             1 / ih=7
net-spec log config

net-spec log 5 \
             4 input-config:"%echo  + + 1  = + +  + -1 =  1 +20+30-48 -10+9" \
             1 / ih=7
net-spec log config

echo " "; echo "--- H"; echo " "

net-spec log 5 \
             5 identity bias-config:"%echo  3 1   = +   1 =  + +  + +" \
             1 / bh=3 ho=9
net-spec log config
data-spec log 5 1 / "%echo 2 3 4 5 6 7" .
model-spec log real 5
net-gen log fix - <<end
0.1 0.2 0.3 0.4 5 6 7 8 9
end
net-display log 0
net-tbl q0q1q2q3 log 0
net-tbl q4q5q6q7q8 log 0
net-grad-test log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0 h
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0
calc "(0.2)*5+(0.3)*6+(0.1+0.2+0.4)*7"

echo " "; echo "--- I"; echo " "

net-spec log 5 \
             5 bias-config:"%echo  3 1   = +   1 =  + +  +3 +3" \
             1 / bh=3 ho=9
net-spec log config
data-spec log 5 1 / "%echo 2 3 4 5 6 7" .
model-spec log real 5
net-gen log fix - <<end
0.1 0.2 0.3 0.4 0.5 0.6 5 6 7 8 9
end
net-display log 0
net-tbl q0q1q2q3q4q5 log 0
net-tbl q6q7q8q9q10 log 0
net-grad-test log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0 h
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0
calc "Tanh(0.2)*5+Tanh(0.3)*6+Tanh(0.1+0.2)*7+Tanh(0.6)*9"

echo " "; echo "--- J"; echo " "

net-spec log 5 5 bias-config:"%echo  3 1   = +   1 =  + +  +3 +3" / bo=3
net-spec log config
data-spec log 5 5 / "%echo 2 3 4 5 6 12 13 14 15 16" .
model-spec log real 5
net-gen log fix - <<end
0.1 0.2 0.3 0.4 0.5 0.6 
end
net-display log 0
net-tbl q0q1q2q3q4q5 log 0
net-grad-test log 0 0.002
net-eval log 0 / 1.1 1.1 0 / 1.2 1.2 0 / 1.3 1.3 0 / 1.4 1.4 0 / 1.5 1.5 0
echo 0.2 0.3 0.3 0 0.6

echo " "; echo "--- K"; echo " "

net-spec log 5 5 input-config:"%echo  2 3 1  4 1 2  5 2 1  1 1 3" / io=3
net-spec log config
data-spec log 5 5 / "%echo 2 3 4 5 6 12 13 14 15 16" .
model-spec log real 5
net-gen log fix - <<end
0.11 0.22 0.33
end
net-display log 0
net-tbl q0q1q2 log 0
net-grad-test log 0 0.002
net-eval log 0 / 10 10 0 / 20 20 0 / 30 30 0 / 40 40 0 / 50 50 0
echo 12.1 5.5 2.2 0 0
