#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 1 2 1 2 1 / ih0=1 hh1=2 hh2=3 h2o=4
net-spec log
data-spec log 1 1 / "%/bin/echo -e 0.8 1.3 \\\\n -0.5 0.3" .
model-spec log real 1
net-gen log fix - <<end
2 -1 
4 3
-1 -2
3 2
end
net-display -h log 0
net-display -p log 0
net-display log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.001

echo " "; echo "--- B"; echo " "

net-spec log 1 2 1 2 1 / ih0=1 ih1=2 h0h2=7 h1h2=3 h2o=4
net-spec log
data-spec log 1 1 / "%/bin/echo -e 0.8 1.3 \\\\n -0.5 0.3" .
model-spec log real 1
net-gen log fix - <<end
2 -1 
3
4 3 2 1
-1 -2
3 2
end
net-display -h log 0
net-display -p log 0
net-display log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.001

echo " "; echo "--- C"; echo " "

net-spec log 1 2 1 2 cfg-h:"%echo 1 1 1" 1 / ih0=1 ih1=2 h0h2=7 h1h2=3 h2o=4
net-spec log config
data-spec log 1 1 / "%/bin/echo -e 0.8 1.3 \\\\n -0.5 0.3" .
model-spec log real 1
net-gen log fix - <<end
2 -1 
3
4 3 2 1
-1
3 2
end
net-display -h log 0
net-display -p log 0
net-display log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.001

echo " "; echo "--- D"; echo " "

net-spec log 1 2 1 2 cfg-h0:"%echo 1 1 1" 1 / ih0=1 ih1=2 h0h2=7 h1h2=3 h2o=4
net-spec log config
data-spec log 1 1 / "%/bin/echo -e 0.8 1.3 \\\\n -0.5 0.3" .
model-spec log real 1
net-gen log fix - <<end
2 -1 
3
1.5 
-1 -2
3 2
end
net-display -h log 0
net-display -p log 0
net-display log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.001
