#!/bin/bash

echo " "; echo "--- A"

net-spec log 3 2 / io=3 bo=4
data-spec log 3 2 / "%echo 100 200 300 7 8" .
model-spec log real 1
net-gen log fix - <<end
2 3 4 5 6 7 40 50
end
net-display log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

echo " "; echo "--- B"

net-spec log 5 2 / io=3 bo=4
data-spec log 5 2 / "%echo 100 7 200 8 300 7 8" .
model-spec log real 1
net-gen log fix - <<end
2 3 0 0 4 5 0 0 6 7 40 50
end
net-display log 0
net-tbl -h o0@o1@ log 0
net-grad-test log 0 0.001

echo " "; echo "--- C"

net-spec log 5 1 / io=3 bo=4
data-spec log 5 1 / "%echo 100 7 200 8 300 7 8" .
model-spec log real 1
net-gen log fix - <<end
2 0 4 0 6 40
end
net-display log 0
net-tbl -h o0@ log 0
net-grad-test log 0 0.001
