#!/bin/bash

echo " "; echo "--- A"; echo " "

net-spec log 36 80 4 / ih=0.1 bh=0.5 ho=0.3 bo=0.7
model-spec log class
data-spec log 36 1 4 / ../ex-image/idata@1:100 .
net-gen log 0
net-grad-test log 0 0.001
net-pred nmp log 0 / ../ex-image/idata@1:10 .

echo " "; echo "--- B"; echo " "

net-spec log 35 81 4 / ih=0.1 bh=0.5 ho=0.3 bo=0.7
model-spec log class
data-spec log 35 1 4 / ../ex-image/idata@1:100,2 .
net-gen log 0
net-grad-test log 0 0.001
net-pred nmp log 0 / ../ex-image/idata@1:10,2 .

echo " "; echo "--- C"; echo " "

net-spec log 34 83 4 / ih=0.1 bh=0.5 ho=0.3 bo=0.7
model-spec log class
data-spec log 34 1 4 / ../ex-image/idata@1:100,3 .
net-gen log 0
net-grad-test log 0 0.001
net-pred nmp log 0 / ../ex-image/idata@1:10,3 .

echo " "; echo "--- D"; echo " "

net-spec log 36 80 cfg-i:iconfig 4 / ih=0.1 bh=0.5 ho=0.3 bo=0.7
model-spec log class
data-spec log 36 1 4 / ../ex-image/idata@1:100 .
net-gen log 0
net-grad-test log 0 0.001
net-pred nmp log 0 / ../ex-image/idata@1:10 .

echo " "; echo "--- E"; echo " "

net-spec log 36 80 cfg-i:iconfig 4 / ti=0.3 ih=0.1 bh=0.5 ho=0.3 bo=0.7
model-spec log class
data-spec log 36 1 4 / ../ex-image/idata@1:100 .
net-gen log 0
net-grad-test log 0 0.001
net-pred nmp log 0 / ../ex-image/idata@1:10 .
