#!/bin/bash

net-spec ilog2 36 80 input-config:iconfig 4 \
          / ih=0.2:2 bh=0.3:2 ho=0.1:3::4 bo=0.1:2
model-spec ilog2 class

data-spec ilog2 36 1 4 / idata-train .

net-gen ilog2 fix 0.1

mc-spec ilog2 repeat 30 heatbath hybrid 100:10 0.12
net-mc ilog2 1

mc-spec ilog2 sample-sigmas heatbath hybrid 500:20 0.3
net-mc ilog2 2

net-tbl h1h2h3h4 ilog2
net-tbl w1@0:3 ilog2
net-tbl mD ilog2
