#!/bin/bash

# export NET_PRECISION=float   # Uncomment to have net models use FP32

(cd util; echo " "; echo "Making programs in util directory"; echo " "; make)
(cd mc;   echo " "; echo "Making programs in mc directory"; echo " "; make)
(cd dist; echo " "; echo "Making programs in dist directory"; echo " "; make)
(cd bvg;  echo " "; echo "Making programs in bvg directory"; echo " "; make)
(cd net;  echo " "; echo "Making programs in net directory"; echo " "; make)
(cd gp;   echo " "; echo "Making programs in gp directory"; echo " "; make)
(cd mix;  echo " "; echo "Making programs in mix directory"; echo " "; make)
(cd dft;  echo " "; echo "Making programs in dft directory"; echo " "; make)
(cd src;  echo " "; echo "Making programs in src directory"; echo " "; make)
(cd mol;  echo " "; echo "Making programs in mol directory"; echo " "; make)

# Uncomment line below to make GPU versions of net programs:

# (cd net;  echo " "; echo "Making GPU net programs"; echo " "; make gpu)

echo " "; echo "Done making programs"; echo " "
