#!/bin/bash

prog=`echo $0 | sed "s/.*\///"`
module=`echo $prog | sed "s/-.*//"`

log=$1
start=$2

if [ x$6 != x -o x$log == x -o x$start == x ]; then
  echo Usage: $module-avesqerr log start [ iters [ step [ end ] ] ]
  exit 1
fi

iters=${3:-$start}
step=${4:-1}
end=${5:-`log-last $log | sed "s/.* //"`}

if [ $start -lt 1 -o $iters -lt 1 -o $iters -gt $start -o $step -lt 1 \
                  -o $end -lt $start ]; then
  echo Usage: $module-avesqerr log start [ iters [ step [ end ] ] ]
  exit 1
fi

for i in `seq $start $step $end`; do
  begin=`calc $i-$iters+1`
  output=`$module-pred ma $log $begin:$i`
  echo $i `echo $output | sed "s/.*://" | sed "s/+-.*//"`
done
