#!/bin/bash

for run in 1 2 3 4; do
  echo RUN $run PERFORMANCE ON ITS VALIDATION SET:
  net-pred mnpa $1.net$run $2 
done

echo PERFORMANCE ON TEST SET USING ALL RUNS:
net-pred mnpa $1.net1 $2 $1.net2 $2 $1.net3 $2 $1.net4 $2 / idata-test .
